Runtime Applications SDK user code validations and exception hierarchy (#440)
Introduce a clear Exception hierarchy, define clear exceptions
related behaviors in SDK interface doc strings, add a bunch of
tests to verify expected exception types and messages and parity
between local an remote modes.

A lot of effort was spent on exception messages to make them clear to
users.
    
+ a few bug fixes and refactorings.

Example Exceptions and their messages:

```
tensorlake.applications.interface.exceptions.SerializationError: Failed to serialize data with pickle serializer: Attempt to pickle Tensorlake Function 'other_function'. It cannot be passed as a function parameter or returned from a Tensorlake Function.
```

```
tensorlake.applications.interface.exceptions.SDKUsageError: Cannot run Tensorlake Future of Tensorlake Function Call other_function(
  1,
), please pass a not running Awaitable instead.
```

```
tensorlake.applications.interface.exceptions.SDKUsageError: Function 'return_map_awaitable' returned Tensorlake Map Operation [
  Tensorlake Function Call other_function(
    1,
  ),
  Tensorlake Function Call other_function(
    2,
  ),
  Tensorlake Function Call other_function(
    3,
  ),
]. A Tensorlake Map Operation can only be used as a function argument, not returned from it.
```